language: go

go:
  - 1.9.x
  - master

env:
  - DEP_VERSION="0.3.2"

notifications:
  email: false

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install: dep ensure

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
